CONFLUENCE_URL      = "https://hearsttech.atlassian.net/wiki"
PARENT_PAGE_ID      = "3984720018"
CONFLUENCE_USER     = "reem.mohanty@hearst.com"
CONFLUENCE_TOKEN    = ""
SPACE_KEY           = "HTSIO"
